#
# [IMPORTANT] `container_name` properties are prefixed by the project name to avoid conflicting with other project volumes
#

services:
  minio:
    container_name: buc_minio_container_${DOCKER_COMPOSE_CONTAINER_NAME_SUFFIX:-default}
    image: minio/minio:RELEASE.2024-10-29T16-01-48Z
    command: ['server', '--console-address', ':9001', '/data']
    environment:
      MINIO_ROOT_USER: ${S3_ACCESS_KEY:-random-key}
      MINIO_ROOT_PASSWORD: ${S3_SECRET_KEY:-random-key}
    volumes:
      - minio:/data
    ports:
      - '${DOCKER_COMPOSE_MINIO_PORT_BINDING:-9000:9000}'
      - '${DOCKER_COMPOSE_MINIO_CONSOLE_PORT_BINDING:-9001:9001}'
    networks:
      - buc
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 1s
      timeout: 3s
      retries: 5

networks:
  buc:
    driver: bridge

volumes:
  minio:
